FROM python:3.10

WORKDIR /app

# dont write pyc files
# dont buffer to stdout/stderr
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

# dependencies
RUN pip install -r requirements.txt
RUN pip install -U python-dotenv

COPY app/ .

# Expose the FastAPI port
EXPOSE 8000

# Install Streamlit
RUN pip install streamlit

# Expose the Streamlit port
EXPOSE 8000

# Run the Streamlit app
CMD ["streamlit", "run", "main.py", "--server.port", "8000"]